### ISSUE TITLE
 Uncaught Error: Call to a member function getFrontend()

### ISSUE THREAD

**Issue by ebofi** [tristanbettany/Magento_2_Product_Labels#1]
When installed on M2, Version 2.2.8, We are getting error when clicking on the products

Fatal error: Uncaught Error: Call to a member function getFrontend() on boolean in /chroot/home/cptech/cphomeorig/public_html/app/code/TPB/ProductLabels/Helper/Data.php:56 Stack trace: #0 /chroot/home/cptech/cphomeorig/public_html/app/code/TPB/ProductLabels/Block/AbstractBlock.php(68): TPB\ProductLabels\Helper\Data->getAttributeData('limited', Object(Magento\Catalog\Model\Product\Interceptor)) #1 /chroot/home/cptech/cphomeorig/public_html/app/code/TPB/ProductLabels/Block/ProductLabels.php(164): TPB\ProductLabels\Block\AbstractBlock->getAttributeData('limited') #2 [internal function]: TPB\ProductLabels\Block\ProductLabels->isProductLimitedEdition() #3 /chroot/home/cptech/cphomeorig/public_html/vendor/magento/framework/View/TemplateEngine/Php.php(82): call_user_func_array(Array, Array) #4 /chroot/home/cptech/cphomeorig/public_html/app/code/TPB/ProductLabels/view/frontend/templates/product_labels.phtml(5): Magento\Framework\View\TemplateEngine\Php->__call('isProductLimite...', Array) #5 /chroot/home/cptech/cphomeorig/public_ in /chroot/home/cptech/cphomeorig/public_html/app/code/TPB/ProductLabels/Helper/Data.php on line 56

**Comment by tristanbettany** [comment]
Very late reply I know, apologies for that, its been about 2 years since I've worked with Magento now. I can't guarantee It will be soon however I will get round to it eventually. from the looks of the error it seems like something may have changed in Magento. If it is possible to test on earlier versions of Magento 2 that would help. Or even a clean install of Magento 2 to verify that it isn't a conflicting extension or theme. Either way the error should not fatal like that and should be caught so thanks and I will update soon :)
